### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dgryski** [dgryski/carbonzipper#12]
If anybody else is going to use the zipper stack, we need do actually document how to set the whole thing up, including configuration and testing that all the moving parts are connected happily.

**Comment by didip** [comment]
If its not too much work, I'd love to read a simple docs on how they are all tied together. Even if it's just a simple ascii art.

**Comment by nnuss** [comment]
ascii art you say?
This is how I'm familiar with the parts fitting together

```pre



     Compute                Routing               Storage              Transport

.........................................................................................
                   .                      .                     .
                   .                      .                     .
     Graphite +----------------+          .     carbonstore <------+
                   .           v          .                     .  |
                   .                      .          ^          .  |
                   .     carbonzipper +--------------+          .  ++ carbon-c-relay
                   .                      .          v          .  |
                   .           ^          .                     .  |
     carbonapi +---------------+          .      carbonmem <-------+
                   .                      .                     .
                   .                      .                     .
                   .                      .                     .
```
Metrics are arrive from the right.
Graphs are drawn on the left (or json is made for Grafana, seyren, bosun etc).

**Comment by didip** [comment]
Thanks! Also, if you don't mind, could you provide config file example for carbon zipper?

**Comment by nnuss** [comment]
```perl
# NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE
#
# A single shell-style (#) comment block may appear at the top of the file
# (it will be stripped off). However, the remainder of the file must be valid JSON.
# (So the `//` comments below will cause it to fail)
#
# NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE
{
    // Listen port
    "Port": 8080,
    
    // Your preferred GOMAXPROCS setting; if you wish to override it in config
    // rather than the environment.
    "MaxProcs": 0,

    // Graphite, "host:port", to send zipper's metrics to.
    "GraphiteHost": "",

    // Interval seconds to send zipper's own metrics.
    "IntervalSec": 60,

    // Number of 100ms buckets to track request distribution in. Used to build
    // 'carbon.zipper.hostname.requests_in_0ms_to_100ms' metric and friends.
    // Requests beyond the last bucket are logged as slow (default of 10 implies "slow" is >1 second).
    "Buckets": 10,

    // Maximum total backend requesting timeout in ms. ( How long we may spend making requests. )
    "TimeoutMs": 10000,

    // Timeout, in ms, once the final backend has been contacted. ( [Effectively] How long we'll wait for the slowest response. )
    "TimeoutMsAfterAllStarted": 2000,

    // Number of concurrent requests to any given backend - default is no limit.
    // If set, you likely want >= MaxIdleConnsPerHost
    "ConcurrencyLimitPerServer": 0,

    // Control http.MaxIdleConnsPerHost. Large values can lead to more idle
    // connections on the backend servers which may bump into limits; tune with care.
    "MaxIdleConnsPerHost": 100,

    // "http://host:port" array of instances of carbonserver stores
    // This is the *ONLY* config element that MUST be specified.
    "Backends":
    [
        "http://10.0.0.1:8080",
        "http://10.0.0.2:8080",
        "http://192.168.0.100:8080",
        "http://192.168.0.200:8080",
        "http://192.168.1.212:8080"
    ]
}
```

**Comment by xneo64** [comment]
@nnuss is carbonmem absolutely critical for proper operation of the stack? Currently I've implemented the stack with only carbonserver(s) in the zipper backend and don't see the benefit / purpose of carbonmem?

**Comment by nnuss** [comment]
@xneo64 carbonmem is a specialized store - it is not necessary in the stack.

The benefit/purpose is:
carbonmem provides a "TopK" glob-like filter over a potentially vast tree.

Suppose we had a publicly available api and were interested in the data sent by ip and endpoint (which you've sent to graphite: tld.my_api.endpoint.action.by_ip.{{ip}} ).

tld.my_api.endpoint.action.by_ip.*.TopK.10min  // where "*" is ip address level, "TopK" is a (streaming) function provided by carbonmem, and "10min" is the argument to it.

The result is the top 100 ips/metrics over 10 minute window during the &from=&until= window you asked for. Useful for identifying large and sudden use by ips.

@dgryski wrote it and I hope he'll fill in any gaps or inaccuracies in my description.

**Comment by dgryski** [comment]
There are a few places where carbonmem really shines is where (in @nnuss's example) you have a *huge* number of IPs.  First, each metric would take up space on disk, which if you have a *huge* number of them, even ones that only visit once or twice, then they have to allocate an entire whisper file.  Second, even though Graphite itself (or carbonapi) can evaluate the "topk" query, it does so by retrieving *all* the data for the glob (which may be hundreds of thousands of metrics in our case) and *then* evaluating it.  Carbonmem does the grouping on the store and only sends back the top 100 metrics.  This is a significant computational and bandwidth win.

The downside of course is that this in-memory index isn't for ever.  You configure a set of number of days, and the data is dropped after that.

**Comment by xneo64** [comment]
Thank you for the explanation - it seems that this component comes in useful when you have a lot of frequent querying for a huge number of metrics. 

I would assume then, that since the advantage here is that the store is in-memory, somewhat volatile _and_ we don't want to commit these metrics to disk, you will have to pre-configure the relay to filter some of this interesting/specific metric traffic only and route that to carbonmem.

**Comment by dgryski** [comment]
Yes; we have rules for https://github.com/grobian/carbon-c-relay that route a specific subset of metrics to the carbonmem instance.  Everything else is routed to one of our many other regular whisper-based storage clusters.
