### ISSUE TITLE
carbonzipper fails to start if it can't connect to graphite

### ISSUE THREAD

**Issue by grobian** [dgryski/carbonzipper#17]
2015/12/02 13:07:05 starting carbonzipper 9054756a4a6725b7190b93f25c75a49185eec3d0
2015/12/02 13:07:05 setting GOMAXPROCS= 24
2015/12/02 13:07:05 Setting concurrencyLimit 2048
2015/12/02 13:07:05 Using graphite host 127.0.0.1:3002
2015/12/02 13:07:05 unable to connect to to graphite: 127.0.0.1:3002:dial tcp 127.0.0.1:3002: getsockopt: connection refused

this is not necessary, I guess it should just keep on trying to connect, but not fail

**Comment by grobian** [comment]
This appears to be a way the g2g library operates.  We can either hack around it using a go routine that tries to establish the initial connection, or we hack the NewGraphite function not to try and connect, since each and every submission function in g2g will reconnect the connection if it got broken.

@dgryski: what's your preference/opinion here?

**Comment by dgryski** [comment]
The "unable to connect to graphite" message is from a log.Fatal() that we control.  I think having a graphite goroutine that does all the initialization is a good idea.

**Comment by grobian** [comment]
bleh, lot of work, and it needs copy-pasting in all our projects ...

**Comment by dgryski** [comment]
We can pull common logic out into a library and make all our stack use it, like I did with mlog.
