### ISSUE TITLE
Fault Tolerence for backend failures?

### ISSUE THREAD

**Issue by jdemod** [dgryski/carbonzipper#9]
If you query against carbonzipper on your frontend graphite webapp, how does it handle backend servers going down? In the traditional graphite stack, I have run into issues whereby the webapp slows to a crawl when one of it's cluster servers goes down. Is this behavior the same with the use of carbonzipper?

**Comment by dgryski** [comment]
There is a 2 second timeout (configurable) that prevents slow/dead stores from disrupting the front-end. At Booking we routinely have stores die and we notice only because our monitoring tells us, not because of user-visible performance degradation of our graphite install.

**Comment by jdemod** [comment]
Good to know, thanks!
